Add property
rahul-tarafdar-synerzip/neo4j-browser pull request #43
Opened 2019-07-12 10:00 UTC by KirthiNair

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip requested changes

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +import { withBus } from 'react-suber'
unused import?

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +import { connect } from 'react-redux'
unused import?

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +// import { PlusIcon } from "browser-components/icons/Icons";
remove commented code

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/shared/modules/itemEditor/itemEditorDuck.js
> +        cmd = `MATCH (a:${action.editPayload.label} {${
use node id for match

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +            'node'
use nodeProperties

2019-07-12 10:10 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +            'update',
user create

2019-07-12 13:18 UTC, KirthiNair commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +import { withBus } from 'react-suber'
done

2019-07-12 13:18 UTC, KirthiNair commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +import { connect } from 'react-redux'
done

2019-07-12 13:18 UTC, KirthiNair commented on src/browser/modules/EditorInfo/DisplayNodeDetails.jsx
> +// import { PlusIcon } from "browser-components/icons/Icons";
done

2019-07-12 13:18 UTC, KirthiNair commented on src/shared/modules/itemEditor/itemEditorDuck.js
> +        cmd = `MATCH (a:${action.editPayload.label} {${
done

2019-07-12 13:18 UTC, KirthiNair commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +            'node'
done

2019-07-12 13:19 UTC, KirthiNair commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +            'update',
done

2019-07-12 13:26 UTC, rahul-tarafdar-synerzip requested changes

2019-07-12 13:26 UTC, rahul-tarafdar-synerzip commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +  function DropDownContents (props) {
get this out of AddProperty component.

2019-07-15 03:39 UTC, KirthiNair commented on src/browser/modules/EditorInfo/AddProperty.jsx
> +  function DropDownContents (props) {
done

2019-07-15 05:42 UTC, rahul-tarafdar-synerzip approved these changes

2019-07-15 05:42 UTC, merged